### PR TITLE
FIX: UI was broken since Jenkins version 2.263

### PR DESCRIPTION
**Pull request by lcharlois-neotys**
It was not possible to change a job configuration when NeoLoad plugin was enabled.

### CODE REVIEW

**Comment by lcharlois-neotys** [comment]
Wating for QA checks.

**Comment by lcharlois-neotys** [comment]
Fix has been validated by QA team.

**Comment by YMasliah-neotys** [comment]
Review ok

**Review by GrayGoose — APPROVED** [review]

**Comment by Absh-Day** [comment]
I tried with 2.239 and built this plugin from source, but pages are still hanging.
Can someone help?

**Comment by lcharlois-neotys** [comment]
Hello @Absh-Day ,

During our test regarding this bug, we seen this issues that was caused by another plugin. Could you try to deactivate other plugin used in your job and check if issue is still there ?

**Comment by Absh-Day** [comment]
> Hello @Absh-Day ,
> 
> During our test regarding this bug, we seen this issues that was caused by another plugin. Could you try to deactivate other plugin used in your job and check if issue is still there ?

I tried removing all plugins that showed up 'Uninstall' button in plugins section, but issue is still the same.
Do you know any specific plugin to watch out?

**Comment by lcharlois-neotys** [comment]
Could you please open an issue on https://issues.jenkins.io/ ?

**Pull request merged**
